/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudienceRouteImport } from './routes/audience'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as PropagationRouteImport } from './routes/propagation'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as TrendsIndexRouteImport } from './routes/trends.index'
import { Route as TrendsTrendIdRouteImport } from './routes/trends.$trendId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceRoute = AudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const PropagationRoute = PropagationRouteImport.update({
  id: '/propagation',
  path: '/propagation',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/trends/',
  path: '/trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsTrendIdRoute = TrendsTrendIdRouteImport.update({
  id: '/trends/$trendId',
  path: '/trends/$trendId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/chatbot': typeof ChatbotRoute
  '/content': typeof ContentRoute
  '/explorer': typeof ExplorerRoute
  '/keywords': typeof KeywordsRoute
  '/platforms': typeof PlatformsRoute
  '/propagation': typeof PropagationRoute
  '/sentiment': typeof SentimentRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/chatbot': typeof ChatbotRoute
  '/content': typeof ContentRoute
  '/explorer': typeof ExplorerRoute
  '/keywords': typeof KeywordsRoute
  '/platforms': typeof PlatformsRoute
  '/propagation': typeof PropagationRoute
  '/sentiment': typeof SentimentRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/trends': typeof TrendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/chatbot': typeof ChatbotRoute
  '/content': typeof ContentRoute
  '/explorer': typeof ExplorerRoute
  '/keywords': typeof KeywordsRoute
  '/platforms': typeof PlatformsRoute
  '/propagation': typeof PropagationRoute
  '/sentiment': typeof SentimentRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/trends/': typeof TrendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audience'
    | '/chatbot'
    | '/content'
    | '/explorer'
    | '/keywords'
    | '/platforms'
    | '/propagation'
    | '/sentiment'
    | '/trends/$trendId'
    | '/trends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audience'
    | '/chatbot'
    | '/content'
    | '/explorer'
    | '/keywords'
    | '/platforms'
    | '/propagation'
    | '/sentiment'
    | '/trends/$trendId'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/audience'
    | '/chatbot'
    | '/content'
    | '/explorer'
    | '/keywords'
    | '/platforms'
    | '/propagation'
    | '/sentiment'
    | '/trends/$trendId'
    | '/trends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudienceRoute: typeof AudienceRoute
  ChatbotRoute: typeof ChatbotRoute
  ContentRoute: typeof ContentRoute
  ExplorerRoute: typeof ExplorerRoute
  KeywordsRoute: typeof KeywordsRoute
  PlatformsRoute: typeof PlatformsRoute
  PropagationRoute: typeof PropagationRoute
  SentimentRoute: typeof SentimentRoute
  TrendsTrendIdRoute: typeof TrendsTrendIdRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audience': {
      id: '/audience'
      path: '/audience'
      fullPath: '/audience'
      preLoaderRoute: typeof AudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propagation': {
      id: '/propagation'
      path: '/propagation'
      fullPath: '/propagation'
      preLoaderRoute: typeof PropagationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/trends'
      fullPath: '/trends/'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/$trendId': {
      id: '/trends/$trendId'
      path: '/trends/$trendId'
      fullPath: '/trends/$trendId'
      preLoaderRoute: typeof TrendsTrendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudienceRoute: AudienceRoute,
  ChatbotRoute: ChatbotRoute,
  ContentRoute: ContentRoute,
  ExplorerRoute: ExplorerRoute,
  KeywordsRoute: KeywordsRoute,
  PlatformsRoute: PlatformsRoute,
  PropagationRoute: PropagationRoute,
  SentimentRoute: SentimentRoute,
  TrendsTrendIdRoute: TrendsTrendIdRoute,
  TrendsIndexRoute: TrendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
